```{r}
library(Seurat)
library(slingshot)
```

```{r}
list.files("~/scripps_hpc_rstudio/gloria_r_folder/9k_brain_e18/raw_data/filtered_gene_bc_matrices/mm10")
```
Using Seurat Pipeline

```{r}
library(ggplot2)

# Load into Seurat
matrix_data <- Read10X(data.dir = "~/scripps_hpc_rstudio/gloria_r_folder/9k_brain_e18/raw_data/filtered_gene_bc_matrices/mm10")
seurat_obj <- CreateSeuratObject(counts = matrix_data, project = "NeuronE18", min.cells = 3, min.features = 200)
```

```{r}
seurat_obj[["RNA"]]@counts         # raw counts
seurat_obj[["RNA"]]@data           # normalized (after NormalizeData())
seurat_obj[["RNA"]]@scale.data     # scaled (after ScaleData())
```


```{r}
head(seurat_obj@meta.data)

```
```{r}
Idents(seurat_obj) <- "seurat_clusters"
```

```{r}
seurat_obj <- NormalizeData(seurat_obj)
seurat_obj <- FindVariableFeatures(seurat_obj)
seurat_obj <- ScaleData(seurat_obj)
seurat_obj <- RunPCA(seurat_obj)
```
```{r}
seurat_obj <- FindNeighbors(seurat_obj, dims = 1:10)
seurat_obj <- FindClusters(seurat_obj, resolution = 0.5)
seurat_obj <- RunUMAP(seurat_obj, dims = 1:10)
```

```{r}
umap_plot <- DimPlot(seurat_obj, reduction = "umap", label = TRUE)

```
```{r}
ggsave("~/scripps_hpc_rstudio/gloria_r_folder/9k_brain_e18/outputs/umap_plot.png", plot = umap_plot, width = 6, height = 5, dpi = 300)
```

```{r}
seurat_obj <- subset(seurat_obj, subset = nFeature_RNA > 200 & nCount_RNA < 7500)
```

```{r}
markers <- FindAllMarkers(seurat_obj, only.pos = TRUE, min.pct = 0.25)
markers

```

```{r}
head(markers)

```
Trajectory inference with Slingshot

```{r}
dimred <- seurat_obj@reductions$umap@cell.embeddings
counts <- as.matrix(seurat_obj@assays$RNA@counts[seurat_obj@assays$RNA@var.features, ])

```

```{r}
clustering <- seurat_obj$RNA_snn_res.0.5
```

```{r}
set.seed(1)
lineages <- getLineages(data = dimred, clusterLabels = clustering)

lineages
```

```{r}
par(mfrow = c(1, 2))
plot(dimred[, 1:2], col=clustering, cex = 0.5, pch = 16)
for (i in levels(clustering)) {
    text(mean(dimred[clustering == i, 1]), mean(dimred[clustering == i, 2]), labels = i, font = 2)
}
plot(dimred[, 1:2], col=clustering,cex = 0.5, pch = 16)
lines(lineages, lwd = 3, col = "black")
```

